- name: curl-github-action
  # You may pin to the exact commit or the version.
  # uses: 4thel00z/curl-github-action@d64ac49148b7905eb7e18a7140e51e6cce7e480e
  uses: 4thel00z/curl-github-action@0.1

---

name: ping

on:
  push:
    branches:
      -main
      -master
      -release/*
    
    steps:
      - name: Ping version
        uses: jtalk/url-health-check-action@v1.4
        with:
          # Check the following URLs one by one sequentially
          url: https://repldm.dupl.repl.co/webhook/update
          # Follow redirects, or just report success on 3xx status codes
          follow-redirect: yes # Optional, defaults to "no"
